name: Deploy Documents Service

on:
  push:
    [cite_start]branches: [ "main" ] # Solo se dispara en main 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el c√≥digo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login en Docker Hub (Necesitas configurar secretos en GitHub)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir y Subir Imagen Docker [cite: 108, 109]
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./InsightFlow.Documents.Api
        file: ./InsightFlow.Documents.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/insightflow-documents:latest

    # 4. Despliegue Continuo a Render (Webhook) [cite: 111]
    # Solo se ejecuta si es un push a main (no en PRs)
    - name: Trigger Render Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}